#!/usr/bin/env ruby

require 'colorize'

def to_map(list, hash={})
    list.each{ |k, v| hash[k] = v }
    hash
end

cmd = to_map(ARGV.map{|arg| arg.split('=') })

USER="keisuganodev"

def disp_timeline(cmd, user, option="l")
    if cmd.keys.include?(option)
        output       = `t timeline #{user}`
        output_lines = output.split("@#{user}")
        output_lines[1..cmd[option].to_i].each do |line|
            puts "@#{user.green} #{line.strip}" if line
        end
    end
end

def get_input()
    print "> "
    $stdin.gets.chomp
end

def collect_message(msg="")
    abort "tweet cancelled" if msg.include?(":exit")
    msg.include?(";") ? msg : collect_message("#{msg} \n#{get_input}")
end

def post_into_timeline(cmd, user, option="p")
    if cmd.keys.include?(option)
        puts "[type :exit to cancel the tweet]"
        output       = `t update "#{collect_message.gsub(';','')}"`
        p output
    end
end

disp_timeline      cmd, USER
post_into_timeline cmd, USER
